/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 lol.gltf --transform 
Files: lol.gltf [4.62MB] > lol-transformed.glb [637.92KB] (86%)
Author: Zemasu (https://sketchfab.com/zemasu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/league-of-legends-new-logo-243f544627214afeb17535ce53ca75fa
Title: League of Legends new Logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/lol-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pPipe2_blinn1_0.geometry} material={materials.blinn1} position={[7.865, 3.205, 11.033]} rotation={[1.725, -0.094, 2.652]} scale={[0.849, 0.103, 0.849]} />
      <mesh geometry={nodes.pPipe2_lolORO_0.geometry} material={materials.lolORO} position={[7.865, 3.205, 11.033]} rotation={[1.725, -0.094, 2.652]} scale={[0.849, 0.103, 0.849]} />
    </group>
  )
}

useGLTF.preload('/lol-transformed.glb')
